apiVersion: v1
kind: Pod
metadata:
  name: tc-sync
  labels:
    tier: api
spec:
  containers:
  - name: tc
    imagePullPolicy: Always
    image: argovis/tc-sync:dev
    command: ['bash', 'parseall.sh']
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 100Mi
        cpu: 100m
  restartPolicy: Never